### ISSUE TITLE
Persisting and restoring aux-nodes

### ISSUE THREAD

**Issue by mike-kelly** [dmx-systems/cytoscape-edge-connections#6]
Thanks for this package!
If I connect a node to an aux-node, I presumably then need to save the aux-node in order to be able to restore the edge connections when reloading the page, as the newly created edge has the id of the aux-node as target.
Do you have an example of persisting and restoring a graph with edge connections? I am having problems loading nodes into cytoscape so that saved aux-nodes are recognised as such by edge-connections.

**Comment by mike-kelly** [comment]
Looking in the source code I don't see any provision for this, so I guess I have to save edges which connect to edge-connectors with the `edgeId` as the target, rather than the aux-node `id`? Then allow edge-connections to dynamically create the aux-nodes when the edges are added?

**Comment by jri** [comment]
> I guess I have to save edges which connect to edge-connectors with the edgeId as the target, rather than the aux-node id? Then allow edge-connections to dynamically create the aux-nodes when the edges are added?

Exactly. You don't have to save aux-nodes. Instead just save the aux-node as target ID. When loading the graph use [`ec.addEdges()`](https://github.com/dmx-systems/cytoscape-edge-connections#api) (instead of `cy.add()`) to add your edges. The aux-nodes are created automatically then. See [`renderTopicmap()`](https://github.com/dmx-systems/dmx-cytoscape-renderer/blob/c96e6c5e14dd813c40c456cb7b0ac65ff0913fd3/src/cytoscape-view.js#L64) as an example.

**Comment by jri** [comment]
I've corrected a mistake

**Comment by mike-kelly** [comment]
Got you, thanks.
